### ISSUE TITLE
Опечатки и неточности

### ISSUE THREAD

**Issue by nzinov** [nzinov/fizteh-seabattle#8]
Добавляйте сюда сообщения об опечатках и неточностях в правилах и всплывающих подсказках в игре.

**Comment by onaga1958** [comment]
Зинов Николай 2014 - должно быть Зинов Николай, 2014   :)

**Comment by onaga1958** [comment]
Перед началом игры игроки расставляют свои наборы фишек произвольным образом на первых 3-х линиях поля - на первых 5-ти же

**Comment by nzinov** [comment]
This issue was moved to nzinov/phystech-seabattle-ng#4
